"""CREATE: table itens.

Revision ID: 10626c5a0bc5
Revises: bfb42dccedf3
Create Date: 2026-05-04 20:33:46.720683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10626c5a0bc5'
down_revision = 'bfb42dccedf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens')
    # ### end Alembic commands ###
